Add login/register components
BinaryStudioAcademy/bsa-winter21-22-codi pull request #10
Opened 2022-02-08 19:43 UTC by VynnykV

2022-02-08 21:15 UTC, tatianahutii requested changes

2022-02-08 21:15 UTC, tatianahutii commented on frontend/src/app/modules/auth/register/register.component.sass
> +  background-color: #0E1525
Could you move all colors to a separate file (something like variables.sass) and import it there?
Please make it in every place with color or some constant values

2022-02-08 21:15 UTC, tatianahutii commented
Could you please add screenshots of these pages?

2022-02-08 22:51 UTC, VynnykV commented
> Could you please add screenshots of these pages?
![Screenshot_1](https://user-images.githubusercontent.com/74214230/153088833-becb72de-aedc-44f2-a0df-47f36a7005c7.png)
![Screenshot_2](https://user-images.githubusercontent.com/74214230/153088839-51abc8b7-3aa6-4dd2-84a5-b05d6012d632.png)

2022-02-09 07:20 UTC, tatianahutii approved these changes

2022-02-09 07:22 UTC, merged