Feature/manage course page
BinaryStudioAcademy/bsa-winter21-22-codi pull request #102
Opened 2022-03-23 22:07 UTC by SayPls

2022-03-24 07:39 UTC, tatianahutii requested changes

2022-03-24 07:39 UTC, tatianahutii commented on backend/Codi.Core/Codi.Core.BLL/Services/CourseService.cs
> +        if (existedCourseUser is not null && existedCourseUser.IsDeleted == false)
```suggestion
        if (existedCourseUser is not null && !existedCourseUser.IsDeleted)
```

2022-03-24 07:39 UTC, tatianahutii commented on backend/Codi.Core/Codi.Core.BLL/Services/CourseService.cs
> +        }
You can just add filter by IsDeleted field when you load existedCourseUser

2022-03-24 07:39 UTC, tatianahutii commented on backend/Codi.Core/Codi.Core.Common/DTO/Course/CourseUserDto.cs
> +
Please delete extra space

2022-03-24 07:39 UTC, tatianahutii commented on backend/Codi.Core/Codi.Core.Common/DTO/Course/CourseUserDto.cs
> +
Please delete extra space

2022-03-24 07:39 UTC, tatianahutii commented on frontend/src/app/core/models/course/course-role.ts
> +    Member = 1
You can don't write numbers here

2022-03-24 07:39 UTC, tatianahutii commented on frontend/src/app/modules/main/course-manage-page/course-invite-dialog/course-invite-dialog.component.html
> +                <a type="button" style="color: #8834ee" *ngIf="!currentCourseUser.courseRole" (click)="deleteUserCourse(courseUser.user.id)" >&#10008;</a>
Please do not use inline styles

2022-03-24 07:39 UTC, tatianahutii commented on frontend/src/app/modules/main/course-manage-page/course-invite-dialog/course-invite-dialog.component.ts
> +        if (term === '') {
```suggestion
        if (!term) {
```

2022-03-24 07:39 UTC, tatianahutii commented on frontend/src/app/modules/main/course-manage-page/course-invite-dialog/course-invite-dialog.component.ts
> +        let invitedUser: CourseUser;
Why do you need this variable?

2022-03-24 07:39 UTC, tatianahutii commented on frontend/src/app/modules/main/course-manage-page/course-invite-dialog/course-invite-dialog.component.ts
> +                    this.reloadCourseUsers( 1 )
Please get rid of this magic number

2022-03-24 07:39 UTC, tatianahutii commented on frontend/src/app/modules/main/course-manage-page/course-invite-dialog/course-invite-dialog.component.ts
> +                    this.reloadCourseUsers(1)
See the previous comment

2022-03-24 07:39 UTC, tatianahutii commented on frontend/src/app/modules/main/course-manage-page/course-invite-dialog/course-invite-dialog.component.ts
> +                    this.reloadCourseUsers(1)
See the previous comment

2022-03-24 07:39 UTC, tatianahutii commented on frontend/src/app/modules/main/course-manage-page/course-manage-page.component.sass
> +        content: ''
Do you really need this?

2022-03-24 07:43 UTC, tatianahutii commented
Could you please add screenshots? 😺

2022-03-24 08:31 UTC, SayPls commented on backend/Codi.Core/Codi.Core.BLL/Services/CourseService.cs
> +        }
I ignore this filter for inviting previously deleted course users from current course

2022-03-24 11:47 UTC, tatianahutii commented on backend/Codi.Core/Codi.Core.BLL/Services/CourseService.cs
> +        }
But you need to filter users, and this field should not affect the result

2022-03-25 19:12 UTC, SayPls commented
![image](https://user-images.githubusercontent.com/93927128/160186344-53e9ac92-dd6b-4419-9b42-6699e5c3ee8f.png)
![image](https://user-images.githubusercontent.com/93927128/160186405-9ded660a-bb7e-4ea5-9f9f-f45ea02e25bb.png)
![image](https://user-images.githubusercontent.com/93927128/160186484-2ecd65e5-fc9f-4f3f-96f7-96cbbc6f5715.png)

2022-03-26 10:59 UTC, tatianahutii approved these changes

2022-03-26 10:59 UTC, tatianahutii commented
LGTM

2022-03-26 10:59 UTC, merged