Fix css, add async validator for course name
BinaryStudioAcademy/bsa-winter21-22-codi pull request #108
Opened 2022-03-27 16:47 UTC by SayPls

2022-03-27 16:53 UTC, ismv requested changes

2022-03-27 16:53 UTC, ismv commented on frontend/src/app/core/validators/course-name.async-validator.ts
> +        return timer(500).pipe(
why do we need a timer here?

2022-03-27 16:53 UTC, ismv commented on frontend/src/app/core/validators/course-name.async-validator.ts
> +                return resp ? { courseNameExists: true} : null
you are returning boolean value already, why do you need a ternary here?

2022-03-27 17:02 UTC, SayPls commented on frontend/src/app/core/validators/course-name.async-validator.ts
> +        return timer(500).pipe(
so that the user has time to enter and does not spam requests

2022-03-27 17:07 UTC, SayPls commented on frontend/src/app/core/validators/course-name.async-validator.ts
> +                return resp ? { courseNameExists: true} : null
because i need to return error or null

2022-03-28 08:59 UTC, ismv approved these changes

2022-03-28 09:05 UTC, merged