Add firebase, Jwt , AuthService, Google provider
BinaryStudioAcademy/bsa-winter21-22-codi pull request #18
Opened 2022-02-10 17:18 UTC by SayPls

Code Rewie

2022-02-10 18:05 UTC, tatianahutii commented on backend/Codi.Core/Codi.Core.WebAPI/Extentions/ServiceCollectionExtensions.cs
> +            });
Why do we need this?

2022-02-10 18:07 UTC, tatianahutii commented on backend/Codi.Core/Codi.Core.WebAPI/Properties/launchSettings.json
> +      "applicationUrl": "https://localhost:7011;http://localhost:5050",
Why did you change it?

2022-02-10 18:09 UTC, tatianahutii commented on frontend/.firebaserc
> +{
Why do we need this?

2022-02-10 18:10 UTC, tatianahutii commented on frontend/angular.json
> +          }
Please remove this

2022-02-10 18:10 UTC, tatianahutii commented on frontend/firebase.json
> +{
Why do we need this?

2022-02-10 18:13 UTC, tatianahutii commented on frontend/src/app/core/interceptors/auth.interceptor.ts
> +    let token = this.authService.getToken();
You need to get a token only one time, not for every request

2022-02-10 18:15 UTC, tatianahutii commented on frontend/src/app/core/models/current-user.ts
> +  email: string | null;
Make these fields optional

2022-02-10 18:16 UTC, tatianahutii commented on frontend/src/app/core/services/auth.service.ts
> +        this.http.post('http://localhosts:5050/token/verify', {token: theToken})
It will not work on production

2022-02-10 18:17 UTC, tatianahutii commented on frontend/src/app/core/services/auth.service.ts
> +    theUser.isSignedIn = false;
Why do we need this?

2022-02-14 15:50 UTC, tatianahutii requested changes

2022-02-14 15:50 UTC, tatianahutii commented on backend/Codi.Core/Codi.Core.WebAPI/Codi.Core.WebAPI.csproj
> +
Do we need this?

2022-02-14 15:50 UTC, tatianahutii commented on frontend/.gitignore
> +.runtimeconfig.json
Why did you add this?

2022-02-14 15:50 UTC, tatianahutii commented on frontend/src/app/app.module.ts
> +        provideAuth(() => getAuth()),
Do we need this?

2022-02-14 15:50 UTC, tatianahutii commented on frontend/src/app/core/interceptors/jwt.interceptor.ts
> +    const isLoggedIn = currentUser && accessToken;
Why do you check a current user?

2022-02-14 15:50 UTC, tatianahutii commented on frontend/src/app/core/services/auth.service.ts
> +} from "@angular/fire/auth";
Please write this is one line

2022-02-14 15:50 UTC, tatianahutii commented on frontend/src/app/core/services/auth.service.ts
> +    })
Do we need this?

2022-02-14 15:52 UTC, SayPls commented on backend/Codi.Core/Codi.Core.WebAPI/Codi.Core.WebAPI.csproj
> +
no

2022-02-14 15:56 UTC, SayPls commented on frontend/src/app/app.module.ts
> +        provideAuth(() => getAuth()),
yes, this is config for firebase

2022-02-14 16:03 UTC, SayPls commented on frontend/src/app/core/services/auth.service.ts
> +} from "@angular/fire/auth";
ok

2022-02-14 16:07 UTC, SayPls commented on frontend/src/app/core/services/auth.service.ts
> +    })
if the token will be stored in a variable, then we don't need storage

2022-02-14 17:42 UTC, tatianahutii commented on frontend/src/app/core/services/auth.service.ts
> +    })
Why? You will need to get it from storage after every page reload

2022-02-14 17:43 UTC, tatianahutii commented on frontend/src/app/core/interceptors/jwt.interceptor.ts
> +    const isLoggedIn = currentUser && accessToken;
I believe it would be better use just token

2022-02-15 13:00 UTC, ismv approved these changes

2022-02-15 13:31 UTC, ismv approved these changes

2022-02-16 07:47 UTC, merged