Feature/user profile
BinaryStudioAcademy/bsa-winter21-22-codi pull request #55
Opened 2022-02-19 11:55 UTC by VynnykV

current user profile(there is no saving user image to db):
![image](https://user-images.githubusercontent.com/74214230/154799659-1d8a5266-cb22-4473-90ca-714da56ec6b2.png)
![image](https://user-images.githubusercontent.com/74214230/154799661-df6c2c87-637d-43be-a8d8-51cc667dd425.png)
another user:
![image](https://user-images.githubusercontent.com/74214230/154799670-8c3fbda6-677b-4684-921a-5e5efe5c7b1d.png)
![image](https://user-images.githubusercontent.com/74214230/154799672-9a519def-16b4-4e84-aeb7-2d0a1959fed8.png)
edit user page:
![image](https://user-images.githubusercontent.com/74214230/154799685-429ffdd4-4fa1-48e6-9188-8e23f5dc6ca7.png)

2022-02-20 10:01 UTC, tatianahutii requested changes

2022-02-20 10:01 UTC, tatianahutii commented on backend/Codi.Core/Codi.Core.WebAPI/Controllers/UsersController.cs
> +    public async Task<ActionResult<UserDto>> GetUserByEmail([FromHeader] string email)
Is there is any reason why did you use FromHeader instead of FromUri?

2022-02-20 20:47 UTC, VynnykV commented on frontend/src/app/modules/main/edit-user-profile-page/edit-user-profile-page.component.ts
> +    }
I have no idea how to do it, because we have notificationService and eventListener here

2022-02-21 14:50 UTC, tatianahutii approved these changes

2022-02-21 16:21 UTC, merged