Update landing page
BinaryStudioAcademy/bsa-winter21-22-codi pull request #69
Opened 2022-03-12 17:11 UTC by SayPls

2022-03-14 08:31 UTC, tatianahutii requested changes

2022-03-14 08:31 UTC, tatianahutii commented on frontend/src/app/modules/landing/landing-content/landing-content.component.html
> +                    <ul>Python(with Turtle)</ul>
It would be better to use enum instead of this

2022-03-14 08:31 UTC, tatianahutii commented on frontend/src/app/modules/landing/landing-content/landing-content.component.sass
> +    grid-template-columns: 150px 150px 150px 150px 150px 150px
Please use **repeat** here

2022-03-14 08:31 UTC, tatianahutii commented on frontend/src/app/modules/landing/landing-content/landing-content.component.sass
> +        grid-template-columns: 120px 120px 120px 120px
See the previous comment

2022-03-14 08:31 UTC, tatianahutii commented on frontend/src/app/modules/landing/landing-content/landing-content.component.ts
> +    isReadMore: boolean = true;
```suggestion
    showMoreLanguages: boolean = true;
```

2022-03-14 08:31 UTC, tatianahutii commented on frontend/src/app/modules/landing/landing-content/landing-content.component.ts
> +    isReadMore: boolean = true;
And by default, it would be better to have it false
And Please change the logic in the component depending on this change

2022-03-14 13:17 UTC, tatianahutii requested changes

2022-03-14 13:17 UTC, tatianahutii commented on frontend/src/app/modules/landing/landing-content/landing-content.component.html
> +            <div class="language-list-content" [ngClass]="{'limitTextHeight': showMoreLanguages === false}">
```suggestion
            <div class="language-list-content" [ngClass]="{'limitTextHeight': !showMoreLanguages">
```

2022-03-14 13:17 UTC, tatianahutii commented on frontend/src/app/modules/landing/landing-content/landing-content.component.ts
> +    enumKeys: any = [];
Please don't use any

2022-03-14 13:17 UTC, tatianahutii commented on frontend/src/app/shared/constants/languages.ts
> +export enum Languages{
```suggestion
export enum Languages {
```

2022-03-14 13:17 UTC, tatianahutii commented on frontend/src/app/shared/constants/languages.ts
> +    'JavaScript',
```suggestion
    JavaScript = 'JavaScript',
```

2022-03-14 13:17 UTC, tatianahutii commented on frontend/src/app/shared/constants/languages.ts
> +    'JavaScript',
Do it for all items

2022-03-14 16:12 UTC, SayPls commented on frontend/src/app/modules/landing/landing-content/landing-content.component.ts
> +        this.enumKeys = Object.keys(this.languages).filter(f => !isNaN(Number(f)));
don't need, found the better solution

2022-03-14 16:12 UTC, SayPls commented on frontend/src/app/shared/constants/languages.ts
> +export enum Languages{
+

2022-03-15 08:24 UTC, tatianahutii approved these changes

2022-03-15 08:33 UTC, tatianahutii commented
LGTM

2022-03-15 08:34 UTC, merged